#!/usr/bin/env python3

#cat /etc/passwd | cut -d : -f 3 | grep -E '^[0-9]{2}$' | sort | uniq

import re
import os
import sys

PATH = "/etc/passwd"
DELIM = ":"
FIELD = 7

cut_list = [line.split(DELIM)[FIELD - 1] for line in open(PATH)]
uniq_list = set(cut_list)

val = sorted(uniq_list)

print(len(val))

